
export const Shoutout2019Data = [
     {
      title: "Navanauts",
      columns: [
        [
          "Ross Aboff",
          "Shannon Alexander Navarro",
          "Jess Alves de Sa",
          "Tomas Apodaca",
          "Jenna Aronow",
          "Barbara Ayala",
          "Sheldon Bachstein",
          "Rohan Bhobe",
          "Alex Bisker",
          "Arin Black",
          "Zoe Blumenfeld",
          "Sheena Bryant",
          "Nicole Budzius",
          "Jessi Bull",
          "James Bursa",
          "Chandra Carney",
          "Mike Case",
          "Melissa Chapman",
          "Tiffany Chen",
          "Eric Chiu",
          "Michael Chouinard",
          "Viviane Crosthwaite",
          "Jim Delloso",
          "Daniella DeVera",
          "Carolyn Dew",
          "Tanner Doshier",
          "Stephan Dyson",
          "Adrienne Era",
          "Sean Fern",
          "Domenic Fichera",
          "Tamar Fox",
          "Ana Garcia Jimenez",
          "Austin Gardner",
          "Genevieve Gaudet",
        ],
        [
          "Afia Genfi",
          "David Goeke",
          "Rutvika Gupta",
          "Brian Hanley",
          "Lisa Hardee",
          "Jacob Harris",
          "Jeffrey Her",
          "Kelli Ho",
          "Sawyer Hollenshead",
          "Billy Powhatan Hunt III",
          "James Hupp",
          "Sha Hwang",
          "Janelle James",
          "Allison Johnson",
          "Tim Jones",
          "Amanda Kennedy",
          "Meghana Khandekar",
          "Joe Kleinschmidt",
          "Yoom Lam",
          "Roger Lam",
          "Laura Lanford",
          "Alice Lemieux",
          "Jodi Leo",
          "Wei Leong",
          "Charlotte Lewis",
          "Andrew Lomax",
          "Sally Maki",
          "Molly McLeod",
          "Martha Michael",
          "Kim Minnick",
          "Christian Monaghan",
          "Ed Mullen",
          "Regina Neal",
          "Brendan Neutra",
          "Ivana Ng",
        ],
        [
          "Alisa Nguyen",
          "Aaron Ogle",
          "Stephanie Owens",
          "Sneha Pai",
          "Lauren Peterson",
          "Ian Petruziello",
          "Rebecca Piazza",
          "Alsia Plybeah",
          "Jessie Posilkin",
          "Maya Praff",
          "Alex Prokop",
          "Angel Quicksey",
          "JC Quirin",
          "Oscar Ramirez",
          "Geronimo Ramos",
          "Rubaiyat Rashid",
          "Amanda Robinson",
          "Nichole Rosamilia",
          "Jim Ruggiero",
          "Frances Ruiz",
          "Ryan Sibley",
          "Mike Smorul",
          "Joanne Stableford",
          "Makaela Stephens",
          "Anke Stohlmann",
          "Cheryl Swirnow",
          "Kat Tipton",
          "Ferris Tseng",
          "Kalvin Wang",
          "Sharon Warner",
          "Sarah White",
          "Lowell Wood",
          "Yang Yang",
          "Kevin Yeh",
          "Loren Yu",
        ],
      ],
    },
     {
      title: "Navalums",
      columns: [
        ["Allison Newman", "Elliot Truslow", "Eli Kim", "Jazmyn Latimer"],
        ["Jia Huang", "Kenshiro Nakagawa", "Mari Puncel", "Mark Benjamin"],
        [
          "Sam Keller",
          "Stephanie Lawrence",
          "Sunil Sadasivan",
          "Xena Ni",
          "Marcos Torres",
        ],
      ],
    },
    {
      title: "Navapartners",
      columns: [
        [
          "18F",
          "Center on Budget and Policy Priorities",
          "Centers for Medicare & Medicaid Services",
        ],
        [
          "Code for America",
          "Department of Veterans Affairs",
          "Digital Service at VA",
          "Digital Services Coalition",
        ],
        [
          "State of Vermont",
          "United States Digital Service",
          "Veterans Affairs Office of Information Technology’s Digital Experience Product Office",
        ],
      ],
    },
    {
      title: "Navatots",
      columns: [["Audrey Isla Marie"],[ "Nathan Ari"]],
    },
   {
      title: "Navapets",
      columns: [
        [
          "Adie",
          "Albus Dumbledog",
          "Annie",
          "Augie",
          "Beau",
          "Beatrice",
          "Belle",
          "Benji",
          "Blondie",
          "Buffy",
          "Charlie",
          "Chloe",
          "Cinder",
          "Dante",
          "Dori",
          "Elizabeth",
          "Ernest “Ernie” Hemingway",
          "Finnegan",
          "Fiona",
          "Fisher",
          "Frankie",
          "Chloe",
          "Garry",
        ],
        [
          "Garfield",
          "Gatsby",
          "Isabella",
          "Jake Hemingway",
          "Jasper",
          "Jinx",
          "Jinxxy",
          "Kirby",
          "Komi",
          "Laika",
          "Leeloo",
          "Lucy",
          "Luna",
          "Luna",
          "Mae",
          "Mao",
          "Marble",
          "Martha",
          "Max",
          "Mitch",
          "Muuaji",
          "Neko",
          "Newton",
          "Oreo",
        ],
        [
          "Oscar",
          "Penny",
          "Polly",
          "Posy",
          "Precious",
          "Radar",
          "Rafaella",
          "Ragnar",
          "(Red) Sonja",
          "Rose",
          "Sasquatch (Sassy)",
          "Scully",
          "Shadow",
          "Spock",
          "Sue",
          "Victoria",
          "Waffie",
          "Waffles",
          "Wilbur",
          "Xingfu",
          "Yeti",
          "Zatoichi",
          "Zhi",
        ],
      ],
    },
];