/**
 * @jest-environment jsdom
 */
import DEI from "../pages/dei";
import { render } from "@testing-library/react";
import { axe, toHaveNoViolations } from "jest-axe";

const test = {
  content: {
    id: "2021",
    title: "Diversity, equity, and inclusion at Nava",
    lead: "To build digital services that are simple, effective, and accessible to all, our teams must reflect the diverse communities we serve across the US.\n",
    introduction:
      "Improving access to government services is essential to rebuilding trust in institutions, strengthening our democracy, and creating a more just society — especially for vulnerable populations.\n\nOur commitment to diversity, inclusion, and equity not only reflects our [values](/values) as a [public benefit corporation](/impact) but also enriches our ability to do this work. By striving to represent all of the people in the US, we’re better equipped to meet our social responsibility to all of the people we serve. And while we’ve made [progress](/impact/public-benefit-reports-2019) in strengthening our team, we still have work to do.\n",
    overview:
      "## Majority BIPOC by 2025\n\nBy 2025, we hope Nava better matches the representation of race and ethnicity in the US by comprising majority Black, Indigenous, and People of Color. To make progress towards that goal over the next year, our leadership team and employee resource groups are working together to build a process for identifying, prioritizing, and addressing inequities across the company.\n",
    resources: {
      introduction:
        "## Support & community\n\nTo help create a welcoming environment where people feel respected and valued, Nava supports several affinity groups. Each Employee Resource Group (ERG) is created by employees to provide community, mentorship, and support. ERGs have annual budgets, organize internal and external activities, and ERG Leads meet monthly with the Executive team to track initiatives and discuss feedback. ERGs contribute to critical conversations about how we can grow as a public benefit corporation and a diverse, equitable, and inclusive workplace.\n",
      groups: [
        {
          title: "earthtones",
          description:
            "The earthtones ERG aims to actively foster a culture which values the contributions of Nava’s Black employees in tangible ways, and celebrates the diverse perspectives and backgrounds they represent. The mission of the earthtones ERG is to focus on organizational issues impacting Black employees, to promote the recruitment, retention, and career mobility of Blacks working in tech at Nava, and beyond, and to use our influence to positively impact the greater Black community.\n",
        },
        {
          title: "Gender equity",
          description:
            "Gender Equity is Nava’s ERG open to all women, genderqueer, agender, and non-binary employees at Nava. They strive to create spaces at Nava where members are empowered to build community, foster discussion, and promote inclusivity on all levels.\n",
        },
        {
          title: "Juntos",
          description:
            "Juntos is a space for employees who have roots in the Latinx-Luso-Hispanic community. Their mission is to encourage and foster Latinx leadership within Nava, to create safe places for members to feel heard, and to educate allies about the Latinx experience.\n",
        },
        {
          title: "Kaleidoscope",
          description:
            "Kaleidoscope celebrates, safeguards, and holds space for LGBTQIA+ people at Nava and beyond. Kaleidoscope members have created a safe place to form relationships with coworkers that are focused on community rather than exchange or development of economic value. Our awesome members include folks who identify as queer, gay, trans, non-binary, dyke, asexual, lesbian, femme, agender, genderqueer, and bi.\n",
        },
      ],
    },
    body: "## Explore the data\n\nNumbers help us track progress but they don’t tell a complete story about the experiences, perspectives, and intersectional identities represented at Nava. To give a sense of how Nava grows and changes, we collect data annually. The way we collect and use data is anonymous, transparent, and consensual. Read more in our [methodology post](https://blog.navapbc.com/sharing-de-i-data-navas-methodology-27ca4dfc69f2).\n\nThe data below was collected on February 5, 2021 and 83 percent of the team responded.\n\nTo try and provide a more accurate representation of race, ethnicity, and gender, the survey allowed people to describe themselves in their own terms, choose more than one option, and/or decline to answer.\n",
  },
  overview: [
    {
      percent: "49",
      description: "of all Nava staff are BIPOC",
      insideBarColor: "sage",
    },
    {
      percent: "56",
      description: "of Nava's executive team are BIPOC",
      insideBarColor: "navy",
    },
  ],
  categories: {
    employee_percentage: {
      display: "All Employees",
      total: 175,
    },
    Individual_Contributor_percentage: {
      display: "Individual Contributors",
      total: 98,
    },
    Team_Lead_percentage: {
      display: "Team Leads",
      total: 15,
    },
    Manager_percentage: {
      display: "Managers",
      total: 44,
    },
    Director_percentage: {
      display: "Directors",
      total: 7,
    },
    VP_percentage: {
      display: "VP & C Suite",
      total: 9,
    },
  },
  race: {
    title: "Race & ethnicity",
    content:
      "Because some people selected multiple options to describe their race and ethnicity,* the numbers below add up to more than 100 percent.**",
    selfReported:
      "* Self-reported identities include: Ashkenazi Jewish, Australasian, and Chicano.",
    noAnswer: "** Two percent prefer not to answer.",
    statistics: [
      {
        race: "African",
        employee_percentage: 2,
        employee_percentage_Multi: 1,
        Individual_Contributor_percentage: 2,
        Individual_Contributor_percentage_Multi: 0,
        Team_Lead_percentage: 0,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 0,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 11,
        VP_percentage_Multi: 11,
        _Multiple: 1,
      },
      {
        race: "African-American/Black",
        employee_percentage: 11,
        employee_percentage_Multi: 3,
        Individual_Contributor_percentage: 16,
        Individual_Contributor_percentage_Multi: 4,
        Team_Lead_percentage: 13,
        Team_Lead_percentage_Multi: 7,
        Manager_percentage: 2,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 11,
        VP_percentage_Multi: 11,
        _Multiple: 3,
      },
      {
        race: "Asian-American",
        employee_percentage: 9,
        employee_percentage_Multi: 5,
        Individual_Contributor_percentage: 9,
        Individual_Contributor_percentage_Multi: 2,
        Team_Lead_percentage: 13,
        Team_Lead_percentage_Multi: 13,
        Manager_percentage: 9,
        Manager_percentage_Multi: 7,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 11,
        VP_percentage_Multi: 11,
        _Multiple: 1,
      },
      {
        race: "East Asian",
        employee_percentage: 7,
        employee_percentage_Multi: 4,
        Individual_Contributor_percentage: 4,
        Individual_Contributor_percentage_Multi: 1,
        Team_Lead_percentage: 13,
        Team_Lead_percentage_Multi: 13,
        Manager_percentage: 12,
        Manager_percentage_Multi: 7,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 22,
        VP_percentage_Multi: 11,
        _Multiple: 1,
      },
      {
        race: "Hispanic/Latinx",
        employee_percentage: 13,
        employee_percentage_Multi: 7,
        Individual_Contributor_percentage: 14,
        Individual_Contributor_percentage_Multi: 8,
        Team_Lead_percentage: 13,
        Team_Lead_percentage_Multi: 13,
        Manager_percentage: 12,
        Manager_percentage_Multi: 5,
        Director_percentage: 14,
        Director_percentage_Multi: 0,
        VP_percentage: 0,
        VP_percentage_Multi: 0,
        _Multiple: 1,
      },
      {
        race: "Middle Eastern",
        employee_percentage: 1,
        employee_percentage_Multi: 0,
        Individual_Contributor_percentage: 1,
        Individual_Contributor_percentage_Multi: 0,
        Team_Lead_percentage: 0,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 0,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 11,
        VP_percentage_Multi: 0,
        _Multiple: 0,
      },
      {
        race: "Native American/Alaska Native/First Nations",
        employee_percentage: 1,
        employee_percentage_Multi: 1,
        Individual_Contributor_percentage: 1,
        Individual_Contributor_percentage_Multi: 1,
        Team_Lead_percentage: 0,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 0,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 11,
        VP_percentage_Multi: 0,
        _Multiple: 0,
      },
      {
        race: "Native Hawaiian/Pacific Islander",
        employee_percentage: 1,
        employee_percentage_Multi: 1,
        Individual_Contributor_percentage: 0,
        Individual_Contributor_percentage_Multi: 0,
        Team_Lead_percentage: 7,
        Team_Lead_percentage_Multi: 7,
        Manager_percentage: 0,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 0,
        VP_percentage_Multi: 0,
        _Multiple: 1,
      },
      {
        race: "Self-reported race/ethnicity",
        employee_percentage: 2,
        employee_percentage_Multi: 1,
        Individual_Contributor_percentage: 1,
        Individual_Contributor_percentage_Multi: 1,
        Team_Lead_percentage: 0,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 5,
        Manager_percentage_Multi: 2,
        Director_percentage: 14,
        Director_percentage_Multi: 0,
        VP_percentage: 0,
        VP_percentage_Multi: 0,
        _Multiple: 1,
      },
      {
        race: "South Asian",
        employee_percentage: 6,
        employee_percentage_Multi: 1,
        Individual_Contributor_percentage: 7,
        Individual_Contributor_percentage_Multi: 1,
        Team_Lead_percentage: 7,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 5,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 0,
        VP_percentage_Multi: 0,
        _Multiple: 1,
      },
      {
        race: "Southeast Asian",
        employee_percentage: 5,
        employee_percentage_Multi: 3,
        Individual_Contributor_percentage: 3,
        Individual_Contributor_percentage_Multi: 1,
        Team_Lead_percentage: 13,
        Team_Lead_percentage_Multi: 13,
        Manager_percentage: 7,
        Manager_percentage_Multi: 7,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 0,
        VP_percentage_Multi: 0,
        _Multiple: 3,
      },
      {
        race: "White/Caucasian",
        employee_percentage: 58,
        employee_percentage_Multi: 7,
        Individual_Contributor_percentage: 54,
        Individual_Contributor_percentage_Multi: 4,
        Team_Lead_percentage: 60,
        Team_Lead_percentage_Multi: 7,
        Manager_percentage: 67,
        Manager_percentage_Multi: 14,
        Director_percentage: 86,
        Director_percentage_Multi: 0,
        VP_percentage: 56,
        VP_percentage_Multi: 11,
        _Multiple: 7,
      },
      {
        race: "People who selected more than one race or ethnicity",
        employee_percentage: 15,
        employee_percentage_Multi: 0,
        Individual_Contributor_percentage: 10,
        Individual_Contributor_percentage_Multi: 0,
        Team_Lead_percentage: 33,
        Team_Lead_percentage_Multi: 0,
        Manager_percentage: 23,
        Manager_percentage_Multi: 0,
        Director_percentage: 0,
        Director_percentage_Multi: 0,
        VP_percentage: 22,
        VP_percentage_Multi: 0,
        _Multiple: 0,
      },
      {
        race: "BIPOC",
        employee_percentage: 49,
        employee_percentage_Multi: 15,
        Individual_Contributor_percentage: 51,
        Individual_Contributor_percentage_Multi: 10,
        Team_Lead_percentage: 47,
        Team_Lead_percentage_Multi: 33,
        Manager_percentage: 47,
        Manager_percentage_Multi: 26,
        Director_percentage: 14,
        Director_percentage_Multi: 0,
        VP_percentage: 56,
        VP_percentage_Multi: 22,
        _Multiple: 0,
      },
    ],
  },
  gender: {
    title: "Gender",
    content:
      "Because some people selected multiple options to describe their race and ethnicity,* the numbers below add up to more than 100 percent.**",
    selfReported: "* Self-reported identities include: Agender.",
    noAnswer: "** Two percent prefer not to answer.",
    statistics: [
      {
        gender: "Female",
        employee_percentage: 48,
        Individual_Contributor_percentage: 40,
        Team_Lead_percentage: 73,
        Manager_percentage: 56,
        Director_percentage: 57,
        VP_percentage: 56,
        _Multiple: 2,
      },
      {
        gender: "Genderqueer",
        employee_percentage: 3,
        Individual_Contributor_percentage: 2,
        Team_Lead_percentage: 7,
        Manager_percentage: 5,
        Director_percentage: 0,
        VP_percentage: 0,
        _Multiple: 60,
      },
      {
        gender: "Male",
        employee_percentage: 47,
        Individual_Contributor_percentage: 56,
        Team_Lead_percentage: 20,
        Manager_percentage: 40,
        Director_percentage: 43,
        VP_percentage: 44,
        _Multiple: 1,
      },
      {
        gender: "Nonbinary",
        employee_percentage: 3,
        Individual_Contributor_percentage: 4,
        Team_Lead_percentage: 13,
        Manager_percentage: 0,
        Director_percentage: 0,
        VP_percentage: 0,
        _Multiple: 83,
      },
      {
        gender: "Transgender",
        employee_percentage: 1,
        Individual_Contributor_percentage: 1,
        Team_Lead_percentage: 7,
        Manager_percentage: 0,
        Director_percentage: 0,
        VP_percentage: 0,
        _Multiple: 2,
      },
      {
        gender: "Self-reported gender",
        employee_percentage: 1,
        Individual_Contributor_percentage: 1,
        Team_Lead_percentage: 0,
        Manager_percentage: 0,
        Director_percentage: 0,
        VP_percentage: 0,
        _Multiple: 0,
      },
      {
        gender: "People who selected more than one gender identity",
        employee_percentage: 3,
        Individual_Contributor_percentage: 3,
        Team_Lead_percentage: 13,
        Manager_percentage: 0,
        Director_percentage: 0,
        VP_percentage: 0,
        _Multiple: 0,
      },
    ],
  },
  additionalIdentities: {
    title: "Additional Identities",
    statistics: [
      {
        category: "LGBTQIA+",
        percentage: 25,
      },
      {
        category: "First-generation college student",
        percentage: 27,
      },
      {
        category: "Caregiver",
        percentage: 30,
      },
      {
        category: "Have a disability",
        percentage: 10,
      },
      {
        category: "Current or former members of the military",
        percentage: 2,
      },
    ],
  },
};
describe("DEI page", () => {
  it("matches snapshot", () => {
    const { asFragment } = render(<DEI reportData={test} />);

    expect(asFragment(<DEI reportData={test} />)).toMatchSnapshot();
  });

  it("has no accessibility violations", async () => {
    const { container } = render(<DEI reportData={test} />);

    const results = await axe(container);
    expect.extend(toHaveNoViolations);
    expect(results).toHaveNoViolations();
  });
});
