/*
Not used
TODO - Decide if should remove or fix before leaving

This component is used on pages autogenerated for each author 
(ex https://www.navapbc.com/authors/alicia-benish)
*/



import { AuthorPostInterface } from "lib/data_models/post_interface";
import Image from "next/image";

const AuthorBioBlock = ({bio, image, slug }:AuthorPostInterface) => {
    return (
    <div className="responsive-container grid grid-cols-12 py-3xl gap-x-md md:gap-x-2xl">
        <div className="col-span-4 ">
            <div className="max-h-[253px] max-w-[350px]">
           {image &&
            <Image 
                src={image.url}
                height={253}
                width={350}
                layout={"responsive"}
                objectFit="cover"
                alt={image.description}
            />
            }
            </div>
        </div>
        <div className="col-span-1"></div>
        <div className="col-span-7">
            <p>
                {bio}
            </p>
        </div>
        
    </div>
    );
}
export default AuthorBioBlock;
